---
id: "6aca013a-2170-4464-baf9-075d5abb4091"
illustration:
- "illustration_190"
illustrationSquare: []
bpmInfo:
- start: -0.03
  bpm: 190.0
songId: "song_190"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "NintyKeven"
chartersRef:
- "people_ninty_keven"
chartId: "chart_6aca013a21704464baf9075d5abb4091"
tags: []
