---
id: "cc508ca6-5d5f-4222-a4a9-3a8cfbaac03e"
illustration: "illustration_algebra"
bpmInfo:
  - start: 1.355
    bpm: 177.0
    beatsPerBar: 4
songId: "song_algebra"
difficulty: "Special"
difficultyValue: 0.0
charter: "Milthm Team"
chartersRef:
  - "people_milthm_team"
chartId: "chart_cc508ca65d5f4222a4a93a8cfbaac03e"
tags:
  - April Fool 2024
