---
id: "14080c32-a16c-464c-b24a-880f1a7e657d"
illustration: "illustration_algebra"
bpmInfo:
- start: 0.0
  bpm: 177.0
  beatsPerBar: 0
songId: "song_algebra"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Akko"
charterRefs:
- "people_akko"
chartId: "chart_14080c32a16c464cb24a880f1a7e657d"
tags: []
