---
id: "9953c1b3-f92a-406c-8ea6-78dbee1b8f71"
illustration: "illustration_bio_engineering"
bpmInfo:
  - start: 0.05
    bpm: 166.0
    beatsPerBar: 0
songId: "song_bio_engineering"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Kiyotsuki"
chartersRef:
  - "people_kiyotsuki"
chartId: "chart_9953c1b3f92a406c8ea678dbee1b8f71"
tags:
  - "RainWorld"
