---
id: "2d6e3256-818b-434e-9980-ee6fcf14a8c7"
illustration: "illustration_blueface"
bpmInfo:
  - start: 0.08
    bpm: 125.0
    beatsPerBar: 0
songId: "song_blueface"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "SakiA vs. TwT"
chartersRef:
  - "people_sakia"
  - "people_tcstwtbhy"
chartId: "chart_2d6e3256818b434e9980ee6fcf14a8c7"
tags:
  - "prolog"
