---
id: "de2327c7-0d63-496f-9974-dbb70bfcbed8"
illustration: "illustration_broken_conviction"
bpmInfo:
- start: 0.07
  bpm: 180.0
  beatsPerBar: 0
songId: "song_broken_conviction"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Akko"
chartersRef:
- "people_akko"
chartId: "chart_de2327c70d63496f9974dbb70bfcbed8"
tags: []
