---
id: "addba2e9-ad45-4770-b850-717ab2e0e17d"
illustration: "illustration_066d5e4fed5580e499f6c278dba3829c"
bpmInfo:
- start: -0.01
  bpm: 145.0
  beatsPerBar: 0
songId: "song_3baa65cfea8e4d0f87f0317126964992"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Akko"
charterRefs:
- "people_akko"
chartId: "chart_addba2e9ad454770b850717ab2e0e17d"
tags: []
