---
id: "a5000e56-b917-40ce-9ebb-12cc2c4a2e70"
illustration: "illustration_4821e24b6cf6fed4089f7f7324f925a8"
bpmInfo:
- start: 0.0
  bpm: 154.0
  beatsPerBar: 0
songId: "song_f33d073236e94662bdfe92ad4a5686f0"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "Akko"
charterRefs:
- "people_akko"
chartId: "chart_a5000e56b91740ce9ebb12cc2c4a2e70"
tags:
- "chapter1"
