---
id: "9953eae4-4f60-4cfe-a8c3-9ada13a4b1ca"
illustration: "illustration_3a92a9d4bbfc8d440bd55e9ccced02e0"
bpmInfo:
- start: 0.0
  bpm: 150.0
  beatsPerBar: 0
songId: "song_e40d6b4068e24adabbe9d9ed9a8e94d5"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "下雨の云"
charterRefs:
- "people_244b50709acc4130a8ac86b5b959ec15"
chartId: "chart_9953eae44f604cfea8c39ada13a4b1ca"
tags:
- "0"
