---
id: "6add3ab9-52c0-4c13-abc9-506dfa89faa6"
illustration: "illustration_402fbad2af03eff4d86e239d6a6f7e43"
bpmInfo:
- start: -0.012
  bpm: 116.0
  beatsPerBar: 0
songId: "song_36336809430d47cfb8d8dd224ad308c0"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Ariayaka"
charterRefs:
- "people_ariayaka"
chartId: "chart_6add3ab952c04c13abc9506dfa89faa6"
tags:
- "RainWorld"
