---
id: "29474d2e-9786-486e-87b1-5dfa5a13552d"
illustration:
- "illustration_chartreuse_green"
illustrationSquare: []
bpmInfo:
- start: 0.666
  bpm: 180.0
songId: "song_chartreuse_green"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "绿色の云"
chartersRef:
- "people_yunmeng"
chartId: "chart_29474d2e9786486e87b15dfa5a13552d"
tags: []
