---
id: "794c0460-7a5e-4ffb-bfcc-2800f1d5bfb2"
illustration: "illustration_df13cbddc62adfc4597277c79980f839"
bpmInfo:
- start: 0.0
  bpm: 174.0
  beatsPerBar: 0
songId: "song_4a2ee6ef96614864bbaaec1a991f4795"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "Kiyotsuki"
charterRefs:
- "people_kiyotsuki"
chartId: "chart_794c04607a5e4ffbbfcc2800f1d5bfb2"
tags: []
