---
id: "7cdb8a2c-e133-4a91-a29f-4e21ba4e442a"
illustration: "illustration_24fbaef1d59b8ea4586f1cc5357893e1"
bpmInfo:
- start: 0.0
  bpm: 97.5
  beatsPerBar: 0
songId: "song_efe065f80aee460f87b9eccae95f73b2"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Milthm Furry Group"
charterRefs:
- "people_e1b67f641d124f1bb848c1fd041f37fb"
chartId: "chart_7cdb8a2ce1334a91a29f4e21ba4e442a"
tags: []
