---
id: "9476c969-d02d-40ca-b64f-eb3efae43ee7"
illustration: "illustration_73d5d81f795c73e45bc2c9827326d715"
bpmInfo:
- start: 0.13
  bpm: 166.0
  beatsPerBar: 3
songId: "song_6321c34dd1764850a27d0595efd01d20"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Akko"
charterRefs:
- "people_akko"
chartId: "chart_9476c969d02d40cab64feb3efae43ee7"
tags:
- "notanote"
