---
id: "6a8d290d-ed98-4842-aa0c-3591d4c9b57e"
illustration:
- "illustration_class_memories"
illustrationSquare: []
bpmInfo:
- start: 0.244
  bpm: 145.0
songId: "song_class_memories"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "papa"
chartersRef:
- "people_papa"
chartId: "chart_class_memories_sprinkle"
tags: []
