---
id: "889ba7a3-ffe1-4c11-8dc3-b2e48da95675"
illustration:
- "illustration_dear"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 114.0
songId: "song_dear"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "Milthm"
chartersRef:
- "people_aeed3353234148c0bc7edf6af3324438"
chartId: "chart_dear_drizzle"
tags: []
