---
id: "7ca7e717-23d8-44c5-8e68-51f74a2f04a0"
illustration:
- "illustration_dear"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 114.0
songId: "song_dear"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Milthm"
chartersRef:
- "people_shuxuezhu"
chartId: "chart_dear_sprinkle"
tags: []
