---
id: "9abbc901-b30f-4145-9b7e-6a6ba9fc3b75"
illustration:
- "illustration_dear"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 114.0
songId: "song_dear"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Kiyotsuki"
chartersRef:
- "people_2fb32c3bbf7c4bf598be4cb8402ab062"
chartId: "chart_dear_cloudburst"
tags: []
