---
id: "0205a17e-c2f1-4335-9703-6a1053761fe4"
illustration:
- "illustration_dum_dum_dum"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 175.0
songId: "song_dum_dum_dum"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Ako! Ako!! Ako!!!"
chartersRef:
- "people_akko"
chartId: "chart_0205a17ec2f1433597036a1053761fe4"
tags: []
