---
id: "eb3b214b-3423-4282-901c-201e3974dc98"
illustration:
- "illustration_dum_dum_dum"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 175.0
songId: "song_dum_dum_dum"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "Milthm"
chartersRef:
- "people_milthm_team"
chartId: "chart_eb3b214b34234282901c201e3974dc98"
tags: []
