---
id: "f7b864bc-72a3-4c9d-ab7c-b57946fb77ec"
illustration: ""
illustrationSquare: "illustration_elsorhg"
bpmInfo:
  - start: -0.003538462
    bpm: 195.0
    beatsPerBar: 4
songId: "song_elsorhg"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "UndefinedViolet"
chartersRef:
  - "people_9bd0029958084551bc0705aba2b58ef4"
chartId: "chart_f7b864bc72a34c9dab7cb57946fb77ec"
tags:
  - "notanote"
