---
id: "b2594118-dcf5-4750-9e57-e4eeef6142fe"
illustration: "illustration_episodic_rain"
bpmInfo:
- start: -0.024
  bpm: 124.0
  beatsPerBar: 0
songId: "song_episodic_rain"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Kiyotsuki"
chartersRef:
- "people_kiyotsuki"
chartId: "chart_b2594118dcf547509e57e4eeef6142fe"
tags: []
