---
id: "cc943369-4a24-4bf7-89b1-34910e02a54c"
illustration:
- "illustration_equinox"
illustrationSquare: []
bpmInfo:
- start: -0.02
  bpm: 190.0
songId: "song_equinox"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "ξιομδγ&ακκο"
chartersRef:
- "people_akko"
- "people_yunmeng"
chartId: "chart_equinox_cloudburst"
tags: []
