---
id: "6ae27070-d580-4776-9600-a31bd71f1fa6"
illustration:
- "illustration_equinox"
illustrationSquare: []
bpmInfo:
- start: 5.06
  bpm: 190.0
songId: "song_equinox"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Ariayaka"
chartersRef:
- "people_ariayaka"
chartId: "chart_equinox_sprinkle"
tags: []
