---
id: "92295644-95d0-451d-90b6-4cdbf2605c82"
illustration:
- "illustration_fantasia_sonata_reflection"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 170.0
songId: "song_fantasia_sonata_reflection"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Kiyotsuki"
chartersRef:
- "people_kiyotsuki"
chartId: "chart_9229564495d0451d90b64cdbf2605c82"
tags: []
