---
id: "c52c18e3-7579-4608-8e7f-b3b873eddfdd"
illustration:
- "illustration_fantasia_sonata_surmount_vanity_aufleben"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 179.0
songId: "song_fantasia_sonata_surmount_vanity_aufleben"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "Eric_Lian & Akko"
chartersRef:
- "people_eric_lian"
- "people_akko"
chartId: "chart_fantasia_sonata_surmount_vanity_aufleben_drizzle"
tags: []
