---
id: "9a53b7e0-fc48-4203-ace2-872a12fe7ec4"
illustration:
  - "illustration_fantasia_sonata_sky_syndrome"
illustrationSquare: [ ]
bpmInfo:
  - start: 0.0
    bpm: 167.0
songId: "song_fantasia_sonata_sky_syndrome"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Kiyotsuki"
chartersRef:
  - "people_kiyotsuki"
chartId: "chart_9a53b7e0fc484203ace2872a12fe7ec4"
tags: [ ]
