---
id: "2026a2ce-b846-4a2a-8dfd-2da0ef02d713"
illustration:
- "illustration_fantasia_sonata_surmount_vanity_aufleben"
illustrationSquare: []
bpmInfo:
- start: 2.975
  bpm: 179.0
songId: "song_fantasia_sonata_surmount_vanity_aufleben"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Akko vs. Ariayaka"
chartersRef:
- "people_akko"
- "people_ariayaka"
chartId: "chart_fantasia_sonata_surmount_vanity_aufleben_cloudburst"
tags: []
