---
id: "36b19d1e-eba2-40a6-bf81-b6a4466b56be"
illustration:
- "illustration_fantasia_sonata_surmount_vanity_aufleben"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 179.0
songId: "song_fantasia_sonata_surmount_vanity_aufleben"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Eric_Lian & Akko & Laugger"
chartersRef:
- "people_eric_lian"
- "people_akko"
- "people_laugger"
chartId: "chart_fantasia_sonata_surmount_vanity_aufleben_sprinkle"
tags: []
