---
id: "20bc960d-564d-43f6-9ddd-a0b732ef3ae7"
illustration:
  - "illustration_fantasia_sonata_god_dance"
illustrationSquare: [ ]
bpmInfo:
  - start: 0.0
    bpm: 177.0
songId: "song_fantasia_sonata_god_dance"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "神と共に舞う「ブルードリーム」"
chartersRef:
  - "people_magazet"
chartId: "chart_20bc960d564d43f69ddda0b732ef3ae7"
tags: [ ]
