---
id: "35ab3fba-928d-4b08-be7f-2fc67a77a838"
illustration: "illustration_fly_to_meteor"
bpmInfo:
  - start: 0.0
    bpm: 180.0
    beatsPerBar: 0
songId: "song_fly_to_meteor_milthm_edit"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "行于繁星的旅人"
chartersRef:
  - "people_yuhuo"
chartId: "chart_35ab3fba928d4b08be7f2fc67a77a838"
tags: [ ]
