---
id: "adcc6c11-2986-4f3c-ae7e-4b52fe75dc83"
illustration: "illustration_fly_to_meteor"
bpmInfo:
- start: 0.0
  bpm: 180.0
  beatsPerBar: 0
songId: "song_fly_to_meteor_milthm_edit"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "仰望夜空的孩童"
charterRefs:
- "people_yuhuo"
chartId: "chart_adcc6c1129864f3cae7e4b52fe75dc83"
tags: []
