---
id: "fee664eb-ec20-4620-bb95-33576965dfc5"
illustration:
- "illustration_furioso_melodia"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 155.0
songId: "song_furioso_melodia"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "nera Magazè"
chartersRef:
- "people_magazet"
chartId: "chart_furioso_melodia_sprinkle"
tags: []
