---
id: "cce9858d-bf0a-47b4-9150-4efd8ef71366"
illustration:
- "illustration_furioso_melodia"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 155.0
songId: "song_furioso_melodia"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "nera Magazè"
chartersRef:
- "people_magazet"
chartId: "chart_furioso_melodia_drizzle"
tags: []
