---
id: "1b392653-c814-4bca-804e-e520f65f2dcc"
illustration:
- "illustration_habitable_zone"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 135.0
songId: "song_habitable_zone"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Magable Zone"
chartersRef:
- "people_magazet"
chartId: "chart_habitable_zone_sprinkle"
tags: []
