---
id: "b16c2048-9a8b-49b0-808d-d2b220cab206"
illustration:
- "illustration_habitable_zone"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 135.0
songId: "song_habitable_zone"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "Magable Zone"
chartersRef:
- "people_magazet"
chartId: "chart_habitable_zone_drizzle"
tags: []
