---
id: "490932e6-484e-495d-98c3-2db660223f3f"
illustration:
- "illustration_habitable_zone"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 135.0
songId: "song_habitable_zone"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Magable Zone"
chartersRef:
- "people_magazet"
chartId: "chart_habitable_zone_cloudburst"
tags: []
