---
id: "04ab586a-fc3c-4969-ab64-eebaa269b40a"
illustration:
- "illustration_heliotrope"
illustrationSquare: []
bpmInfo:
- start: 0.15
  bpm: 172.0
songId: "song_heliotrope"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Magazet (with Matrix) praying for the rain"
chartersRef:
- "people_0842a27178654e8c98c5cb8bf18575a9"
chartId: "chart_heliotrope_cloudburst"
tags: []
