---
id: "484943ed-182b-486c-ac03-714c93f6606a"
illustration:
- "illustration_heliotrope"
illustrationSquare: []
bpmInfo:
- start: 0.11
  bpm: 172.0
songId: "song_heliotrope"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "BlueDream0"
chartersRef:
- "people_d12e740c841c430384146f0fc37f075b"
chartId: "chart_heliotrope_drizzle"
tags: []
