---
id: "cf027460-32a4-49a6-8eaa-6c4eb7161fa5"
illustration:
- "illustration_heliotrope"
illustrationSquare: []
bpmInfo:
- start: 0.11
  bpm: 172.0
songId: "song_heliotrope"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "BlueDream0"
chartersRef:
- "people_magazet"
chartId: "chart_heliotrope_sprinkle"
tags: []
