---
id: "2f838c27-b4c5-4609-9848-29096e912277"
illustration:
  - "illustration_hoshifuru_yoruni"
illustrationSquare: [ ]
bpmInfo:
  - start: -0.01
    bpm: 99.0
songId: "song_hoshifuru_yoruni"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Akko"
chartersRef:
  - "people_akko"
chartId: "chart_2f838c27b4c54609984829096e912277"
tags: [ ]
