---
id: "3fee30c3-a5c9-490d-8dda-1c84c56b685f"
illustration:
  - "illustration_hoshifuru_yoruni"
illustrationSquare: [ ]
bpmInfo:
  - start: -0.01
    bpm: 99.0
songId: "song_hoshifuru_yoruni"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Akko"
chartersRef:
  - "people_akko"
chartId: "chart_3fee30c3a5c9490d8dda1c84c56b685f"
tags: [ ]
