---
id: "0a4a79f4-5d5e-4b15-bf7a-9dec166d28b2"
illustration:
- "illustration_houen_ranka"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 194.0
songId: "song_houen_ranka"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "ηοομ"
chartersRef:
- "people_iblcya"
chartId: "chart_houen_ranka_drizzle"
tags: []
