---
id: "74e0fc4b-5d08-40ba-bff1-48a0bbf86e15"
illustration:
- "illustration_houen_ranka"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 194.0
songId: "song_houen_ranka"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "ηοομ"
chartersRef:
- "people_iblcya"
chartId: "chart_houen_ranka_sprinkle"
tags: []
