---
id: "2b837dbd-4892-42db-ba54-7d4b0bfa8531"
illustration:
- "illustration_houen_ranka"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 194.0
songId: "song_houen_ranka"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "飛原千歌"
chartersRef:
- "people_iblcya"
chartId: "chart_houen_ranka_cloudburst"
tags: []
