---
id: "e7cd8b7f-a19c-488d-b9b6-127524586ed3"
illustration: "illustration_in"
bpmInfo:
  - start: 0.0
    bpm: 133.0
    beatsPerBar: 0
songId: "song_in"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "partIclNstuz"
chartersRef:
  - "people_akko"
chartId: "chart_e7cd8b7fa19c488db9b6127524586ed3"
tags: [ ]
