---
id: "9e083951-188f-4998-951a-58d08b4b4f45"
illustration: "illustration_jump_out"
bpmInfo:
- start: 0.0
  bpm: 174.0
  beatsPerBar: 0
songId: "song_jump_out"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "[Anonymous]"
chartersRef:
- "people_tcstwtbhy"
chartId: "chart_9e083951188f4998951a58d08b4b4f45"
tags:
- "0"
