---
id: "91bc0186-ecba-4b27-8f9c-e09261c2ea03"
illustration:
- "illustration_kaede"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 177.0
songId: "song_kaede"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "TCSTWTBHY"
chartersRef:
- "people_tcstwtbhy"
chartId: "chart_kaede_cloudburst"
tags: []
