---
id: "43ec02b7-4b84-4ea2-a7c4-a52bc8c67022"
illustration:
- "illustration_kaede"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 177.0
songId: "song_kaede"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "TCSTWTBHY"
chartersRef:
- "people_tcstwtbhy"
chartId: "chart_kaede_drizzle"
tags: []
