---
id: "792349e0-2a1f-48b1-a4a5-874394badfc7"
illustration:
- "illustration_kaede"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 177.0
songId: "song_kaede"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "`9E8E"
chartersRef:
- "people_icier"
chartId: "chart_kaede_sprinkle"
tags: []
