---
id: "76aebcf6-d55d-4490-b48a-1fc3162a974a"
illustration: "illustration_kasane"
bpmInfo:
- start: 0.0
  bpm: 190.0
  beatsPerBar: 0
songId: "song_kasane"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "母鸡Sama"
chartersRef:
- "people_muji"
chartId: "chart_76aebcf6d55d4490b48a1fc3162a974a"
tags: []
