---
id: "1ddcf9c9-77d6-4d3e-8a3b-17a7a199a305"
illustration:
- "illustration_la_fouldre"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 214.0
songId: "song_la_fouldre"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Un rêve sans fin (a.k.a Matrix)"
chartersRef:
- "people_9db520f94d384a15884690e2b3e80261"
chartId: "chart_la_fouldre_cloudburst"
tags: []
