---
id: "809946a4-eedd-4e06-b29d-6f6853a68250"
illustration:
- "illustration_life_garden"
illustrationSquare: []
bpmInfo:
- start: -0.013
  bpm: 149.0
songId: "song_life_garden"
difficulty: "Special"
difficultyValue: 0.0
charter: "Akko & XZADUDU179"
chartersRef:
- "people_akko"
- "people_xzadudu179"
chartId: "chart_life_garden_special"
tags: []
