---
id: "2031d629-621a-4af8-849a-e713fac031fc"
illustration:
- "illustration_liulise"
illustrationSquare: []
bpmInfo:
- start: 3.969
  bpm: 120.0
songId: "song_liulise"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "Eric_Lian ＆ yy"
chartersRef:
- "people_eric_lian"
- "people_wuxianyi"
chartId: "chart_drizzle"
tags: []
