---
id: "001f7fdf-9340-441a-8199-8540334bbca0"
illustration:
- "illustration_liulise"
illustrationSquare: []
bpmInfo:
- start: 3.969
  bpm: 120.0
songId: "song_liulise"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Eric_Lian ＆ yy"
chartersRef:
  - "people_eric_lian"
  - "people_wuxianyi"
chartId: "chart_sprinkle"
tags: []
