---
id: "9185b046-aa6c-458e-a60d-c03103cb2c7e"
illustration:
- "illustration_lots_of_spices"
illustrationSquare: []
bpmInfo:
- start: 0.025
  bpm: 198.0
songId: "song_lots_of_spices"
difficulty: "Special"
difficultyValue: 0.0
charter: "xzadudu179?"
chartersRef:
- "people_xzadudu179"
chartId: "chart_lots_of_spices_special"
tags: []
