---
id: "61f5e310-d45b-40dc-a934-e3a849382729"
illustration: "illustration_moonflutter"
bpmInfo:
- start: 0.0
  bpm: 174.0
  beatsPerBar: 0
songId: "song_moonflutter"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "云梦 % xzadudu179"
charterRefs:
- "people_yunmeng"
- "people_xzadudu179"
chartId: "chart_61f5e310d45b40dca934e3a849382729"
tags: []
