---
id: "aafec4af-3479-445b-9b30-b6822b9f5e19"
illustration: "illustration_moving_on"
bpmInfo:
  - start: 0.0
    bpm: 180.0
    beatsPerBar: 0
songId: "song_moving_on"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "海盐焗奇诺TwT"
chartersRef:
  - "people_tcstwtbhy"
chartId: "chart_aafec4af3479445b9b30b6822b9f5e19"
tags:
  - "0"
