---
id: "5bf7cb40-f40b-4ed6-9c4f-788fd0a7011c"
illustration:
- "illustration_nifeiyu"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 174.0
songId: "song_nifeiyu"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "yy"
chartersRef:
- "people_wuxianyi"
chartId: "chart_drizzle"
tags: []
