---
id: "2484331f-4345-4f97-98ac-edda4be3f723"
illustration: "illustration_psyched_fevereiro"
bpmInfo:
- start: -0.04
  bpm: 150.0
  beatsPerBar: 0
songId: "song_psyched_fevereiro"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "Psyched Akko"
chartersRef:
- "people_akko"
chartId: "chart_2484331f43454f9798acedda4be3f723"
tags: []
