---
id: "fade3cf6-1d38-4ebf-b92b-8337f9c7f08d"
illustration:
- "illustration_recall_memories"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 175.0
songId: "song_recall_memories"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "堊裏"
chartersRef:
- "people_dc27204ac6124e2088b67554ae0f95c5"
chartId: "chart_recall_memories_cloudburst"
tags: []
