---
id: "e67fce9f-05c5-4a1a-bfec-bfc1cf153454"
illustration:
- "illustration_recall_memories"
illustrationSquare: []
bpmInfo:
- start: -0.03
  bpm: 175.0
songId: "song_recall_memories"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "Akko"
chartersRef:
- "people_833bb78043324ded813f1c02b12eba87"
chartId: "chart_recall_memories_drizzle"
tags: []
