---
id: "725abac1-5de5-463f-870d-a99a41cae61e"
illustration: "illustration_reminiscence_in_starlight"
bpmInfo:
- start: -0.02
  bpm: 170.0
  beatsPerBar: 0
songId: "song_reminiscence_in_starlight"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Akko"
chartersRef:
- "people_akko"
chartId: "chart_725abac15de5463f870da99a41cae61e"
tags: []
