---
id: "84b880e8-a475-4753-a1fd-cf47b838c959"
illustration:
- "illustration_rustala"
illustrationSquare: []
bpmInfo:
- start: 0.059
  bpm: 190.0
- start: 116.26
  bpm: 184.0
songId: "song_rustala"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "点缀星空"
chartersRef:
- "people_dianzhuixingkong"
chartId: "chart_rustala_cloudburst"
tags: []
