---
id: "fb2fb6ef-16d5-4e33-84f6-222537510dbf"
illustration:
- "illustration_rustala"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 190.0
songId: "song_rustala"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "vitamin b"
chartersRef:
- "people_vitamin_b"
chartId: "chart_rustala_sprinkle"
tags: []
