---
id: "a8010a3f-3286-4d88-99d7-6997a3e116b0"
illustration:
- "illustration_rustala"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 190.0
songId: "song_rustala"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "vitamin b"
chartersRef:
- "people_19537f23127a4d79a8d2f8fd2419eb27"
chartId: "chart_rustala_drizzle"
tags: []
