---
id: "680ba71d-ac5c-438b-9444-e44420a5e44d"
illustration:
- "illustration_sakuyahime"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 148.0
songId: "song_sakuyahime"
difficulty: "Drizzle_Story"
difficultyValue: 0.0
charter: "Kiyotsuki"
chartersRef:
- "people_kiyotsuki"
chartId: "chart_680ba71dac5c438b9444e44420a5e44d"
tags: []
