---
id: "4dc25ee3-2191-4c6e-9555-630f2ed495f6"
illustration:
- "illustration_sakuyahime"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 148.0
songId: "song_sakuyahime"
difficulty: "Cloudburst_Story"
difficultyValue: 0.0
charter: "Kiyotsuki"
chartersRef:
- "people_kiyotsuki"
chartId: "chart_4dc25ee321914c6e9555630f2ed495f6"
tags: []
