---
id: "155a65f9-ac72-485a-8174-8831a525e804"
illustration:
- "illustration_sakuyahime"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 148.0
songId: "song_sakuyahime"
difficulty: "Sprinkle_Story"
difficultyValue: 0.0
charter: "Kiyotsuki"
chartersRef:
- "people_kiyotsuki"
chartId: "chart_155a65f9ac72485a81748831a525e804"
tags: []
