---
id: "f623583b-0605-4db1-b1f2-8849b6fd3a8a"
illustration:
- "illustration_siroirono_yumede"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 159.0
songId: "song_siroirono_yumede"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "青い、夢の終点。"
chartersRef:
- "people_magazet"
chartId: "chart_siroirono_yumede_cloudburst"
tags: []
