---
id: "c434e929-5c50-40ae-b60c-405d2a52f4f2"
illustration:
- "illustration_siroirono_yumede"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 159.0
songId: "song_siroirono_yumede"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "青い、夢の終点。"
chartersRef:
- "people_magazet"
chartId: "chart_siroirono_yumede_drizzle"
tags: []
