---
id: "74255ef3-d07c-4a8d-adc2-5409f476fd6b"
illustration:
- "illustration_siroirono_yumede"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 159.0
songId: "song_siroirono_yumede"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "青い、夢の終点。"
chartersRef:
- "people_magazet"
chartId: "chart_siroirono_yumede_sprinkle"
tags: []
