---
id: "328fac8f-0e32-4e4e-9e43-e623b35f8b87"
illustration:
- "illustration_splash_the_beat"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 202.0
songId: "song_splash_the_beat"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "Kiyotsuki"
chartersRef:
- "people_kiyotsuki"
chartId: "chart_328fac8f0e324e4e9e43e623b35f8b87"
tags: []
