---
id: "6ae27070-d580-4776-9600-a31bd71f1fa6"
illustration:
- "illustration_squinoch"
illustrationSquare: []
bpmInfo:
- start: 5.06
  bpm: 190.0
songId: "song_squinoch"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Ariayaka"
chartersRef:
- "people_d8c28cac2c0842e6a7d78bb6b0c9db95"
chartId: "chart_squinoch_sprinkle"
tags: []
