---
id: "a0efe218-47c0-4699-b9dc-fc2a7e629416"
illustration:
- "illustration_tales_of_misery"
illustrationSquare: []
bpmInfo:
- start: 1.511
  bpm: 160.0
songId: "song_tales_of_misery"
difficulty: "Drizzle"
difficultyValue: 0.0
charter: "Tales of /Transtar/"
chartersRef:
- "people_jiangpian"
chartId: "chart_tales_of_misery_drizzle"
tags: []
