---
id: "c8b5a5d5-38a4-42dd-acc5-38f2db344958"
illustration:
- "illustration_tales_of_misery"
illustrationSquare: []
bpmInfo:
- start: 1.511
  bpm: 160.0
songId: "song_tales_of_misery"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "Tales of 🐕 & 🐉"
chartersRef:
- "people_akko"
- "people_shuxuezhu"
chartId: "chart_tales_of_misery_sprinkle"
tags: []
