---
id: "2fe81998-a979-47e9-80d3-05001a5e0403"
illustration:
- "illustration_tales_of_misery"
illustrationSquare: []
bpmInfo:
- start: 1.511
  bpm: 160.0
songId: "song_tales_of_misery"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "Akko -Misery of Tales-"
chartersRef:
- "people_1eb3cdb36a8d4799bed204ddaab9aac0"
chartId: "chart_tales_of_misery_cloudburst"
tags: []
