---
id: "8d2f4318-f657-4ccb-83de-57ee9e96ae7e"
illustration:
- "illustration_tsukuyomi"
illustrationSquare: []
bpmInfo:
- start: 0.0
  bpm: 176.0
songId: "song_tsukuyomi"
difficulty: "Sprinkle"
difficultyValue: 0.0
charter: "YY vs LL + LLLLLL"
chartersRef:
- "people_wuxianyi"
- "people_leitimo"
- "people_kiyotsuki"
chartId: "chart_tsukuyomi_sprinkle"
tags: []
