---
id: "f3b5c7fc-fdae-417f-8e2c-59fdaf8f9390"
illustration:
- "illustration_tsukuyomi"
illustrationSquare: [ ]
bpmInfo:
- start: 0.0
  bpm: 176.0
songId: "song_tsukuyomi"
difficulty: "Cloudburst"
difficultyValue: 0.0
charter: "YY vs LL"
chartersRef:
- "people_wuxianyi"
- "people_leitimo"
chartId: "chart_tsukuyomi_cloudburst"
tags: [ ]
